# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UNKBOT.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cUNKBOT.proto\x12\x06UNKBOT\"\x1c\n\nUNKRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1f\n\x0bUNKResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\x1e\n\x0cTrainRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"!\n\rTrainResponse\x12\x10\n\x08response\x18\x01 \x01(\t2}\n\nUNKService\x12\x35\n\nPrompt_Bot\x12\x12.UNKBOT.UNKRequest\x1a\x13.UNKBOT.UNKResponse\x12\x38\n\tTrain_Bot\x12\x14.UNKBOT.TrainRequest\x1a\x15.UNKBOT.TrainResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UNKBOT_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UNKREQUEST']._serialized_start=24
  _globals['_UNKREQUEST']._serialized_end=52
  _globals['_UNKRESPONSE']._serialized_start=54
  _globals['_UNKRESPONSE']._serialized_end=85
  _globals['_TRAINREQUEST']._serialized_start=87
  _globals['_TRAINREQUEST']._serialized_end=117
  _globals['_TRAINRESPONSE']._serialized_start=119
  _globals['_TRAINRESPONSE']._serialized_end=152
  _globals['_UNKSERVICE']._serialized_start=154
  _globals['_UNKSERVICE']._serialized_end=279
# @@protoc_insertion_point(module_scope)
