# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import UNKBOT_pb2 as UNKBOT__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in UNKBOT_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class UNKServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prompt_Bot = channel.unary_unary(
                '/UNKBOT.UNKService/Prompt_Bot',
                request_serializer=UNKBOT__pb2.UNKRequest.SerializeToString,
                response_deserializer=UNKBOT__pb2.UNKResponse.FromString,
                _registered_method=True)
        self.Train_Bot = channel.unary_unary(
                '/UNKBOT.UNKService/Train_Bot',
                request_serializer=UNKBOT__pb2.TrainRequest.SerializeToString,
                response_deserializer=UNKBOT__pb2.TrainResponse.FromString,
                _registered_method=True)


class UNKServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Prompt_Bot(self, request, context):
        """returns the result of the UNK request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Train_Bot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UNKServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prompt_Bot': grpc.unary_unary_rpc_method_handler(
                    servicer.Prompt_Bot,
                    request_deserializer=UNKBOT__pb2.UNKRequest.FromString,
                    response_serializer=UNKBOT__pb2.UNKResponse.SerializeToString,
            ),
            'Train_Bot': grpc.unary_unary_rpc_method_handler(
                    servicer.Train_Bot,
                    request_deserializer=UNKBOT__pb2.TrainRequest.FromString,
                    response_serializer=UNKBOT__pb2.TrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UNKBOT.UNKService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UNKService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Prompt_Bot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UNKBOT.UNKService/Prompt_Bot',
            UNKBOT__pb2.UNKRequest.SerializeToString,
            UNKBOT__pb2.UNKResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Train_Bot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UNKBOT.UNKService/Train_Bot',
            UNKBOT__pb2.TrainRequest.SerializeToString,
            UNKBOT__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
